services:
  webfetcher:
    image: ghcr.io/mitslabo/webfetcher:${WEBFETCHER_TAG:-latest}
    container_name: webfetcher
    env_file:
      - .env
    environment:
      - CHROME_CDP_URL=http://lightpanda:9222
      - WEBFETCHER_LOG_LEVEL=${WEBFETCHER_LOG_LEVEL}
    depends_on:
      - lightpanda
    volumes:
      - ./certs:/usr/local/share/ca-certificates
    ports:
      - "8000:8000"
    networks:
      - webfetcher_network

  lightpanda:
    image: ghcr.io/mitslabo/webfetcher-lightpanda:${LIGHTPANDA_TAG:-latest}
    container_name: lightpanda
    env_file:
      - .env
    environment:
      - LIGHTPANDA_ADVERTISE_HOST=lightpanda
      - LIGHTPANDA_LOG_LEVEL=${LIGHTPANDA_LOG_LEVEL}
    volumes:
      - ./certs:/usr/local/share/ca-certificates
    networks:
      - webfetcher_network

networks:
  webfetcher_network:
    driver: bridge
